sudo: required

services:
  - docker

language: python

matrix:
  include:
    - dist: xenial
      python: 3.5

    - dist: xenial
      python: 3.6

    - dist: trusty
      python: 3.6.1

    - dist: xenial
      python: 3.7

    - dist: xenial
      python: 3.8-dev

install:
  - pip3 install '.[dev]'

before_script:
  - git clone https://github.com/nextstrain/zika-tutorial

script:
  - pytest -v
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
  - nextstrain build zika-tutorial
