sudo: required

services:
  - docker

language: python

python:
  - "3.6"
  - "3.7-dev"

install:
  - pip3 install .
  - pip3 install mypy

before_script:
  - git clone https://github.com/nextstrain/zika-tutorial

script:
  - mypy nextstrain
  - nextstrain version
  - nextstrain check-setup
  - nextstrain update
  - nextstrain build zika-tutorial
